### PR TITLE
Config changes

### PR DESCRIPTION
**Pull request by lwahlmeier**

### CODE REVIEW

**Review by medavisjr — APPROVED** [review]
Looks good; so we would need to provide the below on the stim CLI to enable the throttling retry? I'm guessing it could go into the config file as well.

`stim deploy -e something -i somewhere --vault-retryOnThrottle=true`

**Comment by lwahlmeier** [comment]
> Looks good; so we would need to provide the below on the stim CLI to enable the throttling retry? I'm guessing it could go into the config file as well.
> 
> `stim deploy -e something -i somewhere --vault-retryOnThrottle=true`

Right now you actually cant set it on the CLI as an arg you would just do something like
`STIM_VAULT_RETRYONTHROTTLE=true; stim deploy -e something -i somewhere`
or you can put it in the stim config.yaml
```
vault:
  retryOnThrottle: true
```
we can add a cli option for it but we dont have good ways of passing cli args from stim deploy into stimpacks yet, techincally this should be a cli option on `stim aws login`

**Comment by hyperbolist** [comment]
Any plans to make retry count configurable?  Otherwise LGTM.

**Review by hyperbolist — APPROVED** [review]

**Comment by lwahlmeier** [comment]
> Any plans to make retry count configurable? Otherwise LGTM.

Yeah might be a good feature to add later

**Pull request merged**
